name: animal_therapy
description: A new Flutter project.
publish_to: 'none'
flutter_share: ^3.0.0
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^1.10.0"
  firebase_auth: "^3.3.0"
  cloud_firestore: "^3.1.0"
  firebase_storage: "^10.2.0"
  firebase_messaging: "^13.1.0"
  provider: "^6.0.1"
  video_player: "^2.2.7"
  flutter_share: "^2.0.0"
  path_provider: "^2.0.5"
  http: "^0.13.3"
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^3.5.6
  youtube_explode_dart: ^1.10.0
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700

