version: '2.1'    
orbs:
  jira: circleci/jira@1.3.1 

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - jira/notify:
          environment_type: production 
          job_type: build 
          scan_commit_body: false 

workflows:
  example-workflow:
    jobs:
      - example-job