version: '2.1'    
orbs:
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - browser-tools/install-browser-tools
workflows:
  example-workflow:
    jobs:
      - example-job